FROM debian:buster-slim as build

RUN apt-get update && apt-get -y install pkg-config curl gcc && apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
# RUN dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN USER=root cargo new --bin easy_park
WORKDIR /easy_park

COPY ./ .
RUN cat docker/toml-stagging.txt > .cargo/config.toml
RUN cat docker/env-stagging.txt > .env
RUN cargo install sqlx-cli
RUN sqlx database create
RUN sqlx migrate run

# RUN rm ./target/release/deps/holodeck*
RUN cargo build --release

FROM debian:buster-slim

COPY --from=build /easy_park/target/release/backend-parking ./easy_park
CMD ["./easy_park"]
