name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always  
  DATABASE_URL: postgresql://easypark_owner:XTVzOpa94InE@ep-damp-meadow-a5a41qis.us-east-2.aws.neon.tech/easypark?sslmode=require
  RUST_LOG: backend_parking=debug

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOs-latest]
        os: [ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v4
    - name: Prepare env
      run: |
          echo "${{ secrets.API_KEY_STAGING }}" > .env
    - name: Prepare toml
      run: |
          echo '[env]' > .cargo/config.toml
          while IFS= read -r line; do
            if [[ "$line" == *"="* ]]; then
              key=$(echo "$line" | cut -d '=' -f 1)
              value=$(echo "$line" | cut -d '=' -f 2-)
              value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
              echo "$key = \"$value\"" >> .cargo/config.toml
            fi
            done < .env

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install --cask docker dockmate
        
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
         image: rsaputra11/easy_park_rust
         tags: ${{ secrets.DOCKER_TAGS }}
         registry: docker.io
         dockerfile: Dockerfile.stage
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} docker.io
          docker stop easy_park_rust || true
          docker rm easy_park_rust || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/easy_park_rust:${{ secrets.DOCKER_TAGS }}
          docker run -d --name easy_park_rust -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/easy_park_rust:${{ secrets.DOCKER_TAGS }}
