name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always  
  DATABASE_URL: postgresql://easypark_owner:XTVzOpa94InE@ep-damp-meadow-a5a41qis.us-east-2.aws.neon.tech/easypark?sslmode=require
  RUST_LOG: backend_parking=debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Instal sqlx
      run: cargo search cargo-sqlx
    - name: Create DB
      run: cargo sqlx database create
    - name: Migrate Table
      run: cargo sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
