name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always  
  DATABASE_URL: postgresql://easypark_owner:XTVzOpa94InE@ep-damp-meadow-a5a41qis.us-east-2.aws.neon.tech/easypark?sslmode=require
  RUST_LOG: backend_parking=debug

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]
        
    steps:
    - uses: actions/checkout@v4
    - name: Prepare env
      run: |
        echo "${{ secrets.API_KEY_STAGING }}" > .env
        echo "${{ secrets.TOML_KEY_STAGGING }}" > .cargo/config.toml
        cat .env 
        cat .cargo/config.toml

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install docker docker-machine

    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
         image: rsaputra11/easy_park_rust
         tags: v1, latest
         registry: docker.io
         dockerfile: Dockerfile.stage
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
