name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always  
  DATABASE_URL: postgresql://easypark_owner:XTVzOpa94InE@ep-damp-meadow-a5a41qis.us-east-2.aws.neon.tech/easypark?sslmode=require
  RUST_LOG: backend_parking=debug

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]
        
    steps:
    - uses: actions/checkout@v4
    - name: Instal sqlx
      run: cargo install sqlx-cli
    - name: Create DB
      run: sqlx database create
    - name: Migrate Table
      run: sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        brew install docker
        colima start

    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: saputra/easypark-backend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
