name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always  
  DATABASE_URL: postgresql://easypark_owner:XTVzOpa94InE@ep-damp-meadow-a5a41qis.us-east-2.aws.neon.tech/easypark?sslmode=require
  RUST_LOG: backend_parking=debug

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOs-latest]
        os: [ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v4
    - name: Prepare env
      run: |
          echo "${{ secrets.API_KEY_STAGING }}" > .env
    - name: Prepare toml
      run: |
          echo '[env]' > .cargo/config.toml
          while IFS= read -r line; do
            if [[ "$line" == *"="* ]]; then
              key=$(echo "$line" | cut -d '=' -f 1)
              value=$(echo "$line" | cut -d '=' -f 2-)
              value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
              echo "$key = \"$value\"" >> .cargo/config.toml
            fi
            done < .env

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install --cask docker dockmate
    - name: Login docker
      uses: docker/login-action@v1
      with: 
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with: 
         push: true
         tags: rsaputra11/easy_park_rust:${{ github.sha }}
         context: ./Dockerfile.stage
         

    # - name: Push to Ec2
      
